### PR TITLE
add new page

### PR DESCRIPTION
**Pull request by xklbr**
New page add

### CODE REVIEW

**Comment by john-kuo** [comment]
Hey @4rturd13, thanks for contributing.  Did you add this site? **https://familytherapyxxx.com** 

If you did, the format should be **"familytherapyxxx.com":!0** under the **pornMap** array

**Comment by xklbr** [comment]
Thanks, it was edited to the correct format

**Comment by john-kuo** [comment]
hello @4rturd13 , thanks for updating.  

It is still not in the right format and it's not in the right array.  You added it to the **banndedList** array.  It should be in the **pornMap** array with this format **"familytherapyxxx.com":!0**.  If you look at the website format inside the pornMap array.

**Comment by john-kuo** [comment]
@4rturd13 thanks.  it's merged ;)

**Pull request merged**
